### ISSUE TITLE
Rename emacs-pgtk to emacs-git-pgtk

### ISSUE THREAD

**Issue by chvp** [nix-community/emacs-overlay#471]
It hasn't been necessary for a while now to run git emacs to have pgtk. I'd prefer to just run `emacs-pgtk` from nixpkgs instead of running on latest git, but the name override makes this annoying.

**Comment by jian-lin** [comment]
Unshadowing Nixpkgs `emacs-pgtk` is a bit tricky.  When renaming an attr, the old name needs to be kept as an alias in this overlay for backward compatibility.  By default, alias is enabled so the `emacs-pgtk` alias in this overlay still shadows the Nixpkgs one.

I guess in this specific case it may be fine to not keep `emacs-pgtk` as an alias.

**Comment by chvp** [comment]
Can we do this in two stages? Make it emit a warning for a few months that users should switch to `emacs-git-pgtk`, and switch the actual behaviour later?

**Comment by jian-lin** [comment]
Sounds good.  I implemented the first stage in https://github.com/nix-community/emacs-overlay/pull/473.

**Comment by AlexSKaye** [comment]
I don't mean to seem impatient, but has there been enough of a warning period to move forward on this? I'm still seeing the odd Emacs build from source (depending on update timing I guess), and even though it's a fairly minor annoyance, it's one I'd really love to see the back of.

**Comment by jian-lin** [comment]
Thanks for the reminder. #500 should close this.
